---
- name: Deploying basics input and forwards output
  hosts: clients
  roles:
    - fedora.linux_system_roles.logging
  vars:
    logging_inputs:
      - name: basic_input
        type: basics
    logging_outputs:
      - name: forward_output
        type: forwards
        severity: info
        target: momonga.localdomain
        tcp_port: 514
    logging_flows:
      - name: flows
        inputs: [basic_input]
        outputs: [forward_output]
