---
- name: Deploying remote input and remote_files output
  hosts: server
  roles:
    - fedora.linux_system_roles.logging
  vars:
    logging_inputs:
      - name: remote_udp_input
        type: remote
        udp_ports: [514, 1514]
      - name: remote_tcp_input
        type: remote
        tcp_ports: [514, 1514]
    logging_outputs:
      - name: remote_files_output
        type: remote_files
    logging_flows:
      - name: flow
        inputs: [remote_udp_input, remote_tcp_input]
        outputs: [remote_files_output]
